<?php

return [
    'basic' => [
        'name' => 'Basic',
        'price_cents' => 0,
        'active' => true,
        'features' => [
            'storefront',
            'catalog_management',
            'product_variants',
            'product_modifiers',
            'checkout',
            'delivery',
            'pickup',
            'order_management',
            'store_customization',
            'team_access',
            'payments_on_delivery',
            'manual_pix',
        ],
    ],

    'pro' => [
        'name' => 'Pro',
        'price_cents' => 0,
        'active' => false,
        'features' => [
            'storefront',
            'catalog_management',
            'product_variants',
            'product_modifiers',
            'checkout',
            'delivery',
            'pickup',
            'order_management',
            'store_customization',
            'team_access',
            'payments_on_delivery',
            'manual_pix',
            'coupons',
            'customer_relationships',
            'reports',
            'whatsapp_notifications',
            'scheduled_catalog',
            'custom_domain',
        ],
    ],

    'premium' => [
        'name' => 'Premium',
        'price_cents' => 0,
        'active' => false,
        'features' => [
            'storefront',
            'catalog_management',
            'product_variants',
            'product_modifiers',
            'checkout',
            'delivery',
            'pickup',
            'order_management',
            'store_customization',
            'team_access',
            'payments_on_delivery',
            'manual_pix',
            'coupons',
            'customer_relationships',
            'reports',
            'whatsapp_notifications',
            'scheduled_catalog',
            'custom_domain',
            'multiple_stores',
            'online_payments',
            'kitchen_display',
            'advanced_reports',
            'api_access',
            'webhooks',
            'white_label',
            'priority_support',
        ],
    ],
];
